databases:
  - name: cip-postgres
    plan: free
    databaseName: cip_db

services:
  - type: web
    runtime: node
    name: college-information-portal
    rootDir: old_files_snapshot
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cip-postgres
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: cip-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cip-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cip-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: cip-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cip-postgres
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
